[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:nextjs]
command=node server.js
directory=/app
user=nextjs
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
user=nextjs
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
