"use client";

import { useMemo } from "react";
import { encodeQr, qrToSvg, type Ecc, type QrMatrix } from "@/lib/qr";

// A scannable QR code, rendered inline as SVG. We always draw dark modules on a
// white field (even in dark mode) so phone cameras keep the contrast they need.
export function QrCode({
  text,
  ecc = "M",
  moduleSize = 8,
  margin = 4,
  className,
  title,
}: {
  text: string;
  ecc?: Ecc;
  moduleSize?: number;
  margin?: number;
  className?: string;
  title?: string;
}) {
  const svg = useMemo(() => {
    if (!text) return "";
    const qr = encodeQr(text, ecc);
    return qrToSvg(qr, { scale: moduleSize, margin });
  }, [text, ecc, moduleSize, margin]);

  if (!svg) return null;
  // The SVG is generated by us from the module matrix (no user text is ever
  // placed into markup), so injecting it is safe.
  return (
    <div
      className={className}
      role="img"
      aria-label={title ?? "QR code"}
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}

// ---- Downloads --------------------------------------------------------------

function triggerDownload(url: string, filename: string) {
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
}

/** Download the QR as a crisp, infinitely-scalable SVG (best for slides/print). */
export function downloadQrSvg(text: string, filename = "qr-code.svg", ecc: Ecc = "M") {
  const svg = qrToSvg(encodeQr(text, ecc), { scale: 12, margin: 4 });
  const url = URL.createObjectURL(new Blob([svg], { type: "image/svg+xml" }));
  triggerDownload(url, filename);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/** Download the QR as a high-resolution PNG (best for pasting into most tools). */
export function downloadQrPng(text: string, filename = "qr-code.png", ecc: Ecc = "M", pixels = 1024) {
  const qr: QrMatrix = encodeQr(text, ecc);
  const margin = 4;
  const total = qr.size + margin * 2;
  const scale = Math.max(1, Math.floor(pixels / total));
  const dim = total * scale;

  const canvas = document.createElement("canvas");
  canvas.width = dim;
  canvas.height = dim;
  const ctx = canvas.getContext("2d");
  if (!ctx) return;
  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, dim, dim);
  ctx.fillStyle = "#0f172a";
  for (let y = 0; y < qr.size; y++) {
    for (let x = 0; x < qr.size; x++) {
      if (qr.modules[y][x]) ctx.fillRect((x + margin) * scale, (y + margin) * scale, scale, scale);
    }
  }
  canvas.toBlob((blob) => {
    if (!blob) return;
    const url = URL.createObjectURL(blob);
    triggerDownload(url, filename);
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }, "image/png");
}
